BTLonWebMovie/Areas/Admin/Controllers/HomeAdminController.cs
using Azure;
using BTLonWebMovie.Helper;
using BTLonWebMovie.Services.API;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ModelAccess.ViewModel;
using X.PagedList;

namespace BTLonWebMovie.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeAdminController : Controller
    {
        private readonly ILogger<HomeAdminController> _logger;
        private APIServices services;
        public HomeAdminController(ILogger<HomeAdminController> logger, IHttpClientFactory factory)
        {
            _logger = logger;
            services = new APIServices(factory);
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("UserId") != null)
            {
                int userId = int.Parse(HttpContext.Session.GetString("UserId"));
                var user = services.getUserById(userId);
                if(user.UserType != 2)
                {
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                ViewBag.Avatar = user.Avatar;                
                return View();
            }
            return RedirectToAction("Login", "Access", new { area = "" });
        }

        public IActionResult MovieCatalog(int? page)
        {
            SetMenuUser();
            int pageSize = 10;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listMovie = services.getAllMovieView().OrderBy(x => x.MovieName);
            PagedList<MovieView> lst = new PagedList<MovieView>(listMovie, pageNumber, pageSize);
            return View(lst);
        }

        [HttpGet]
        public IActionResult DetailMovie(int movieId)
        {
            SetMenuUser();
            var movie = services.getMovieById(movieId);
            return View(movie);
        }

        [HttpGet]
        public IActionResult CreateMovie()
        {
            SetMenuUser();
            return View();
        }

        [HttpPost]
        public IActionResult CreateMovie(MovieView movie)
        {
            SetMenuUser();
            movie.IsDelete = false;
            var result = services.createMovie(movie);
            if (result)
            {
                return RedirectToAction("MovieCatalog");
            }
            return View(movie);
        }

        [HttpGet]
        public IActionResult EditMovie(int movieId)
        {
            SetMenuUser();
            var movie = services.getMovieById(movieId);
            return View(movie);
        }

        [HttpPost]
        public IActionResult EditMovie(MovieView movie)
        {
            SetMenuUser();
            var result = services.editMovie(movie);
            if (result)
            {
                return RedirectToAction("MovieCatalog");
            }
            return View(movie);
        }

        public IActionResult DeleteMovie(int movieId)
        {
            SetMenuUser();
            TempData["Message"] = "";
            var result = services.deleteMovie(movieId);
            if (result)
            {
                TempData["Message"] = "Phim này đã được xóa";
            }
            return RedirectToAction("MovieCatalog");
        }

        public IActionResult DeletedMovies(int? page)
        {
            SetMenuUser();
            int pageSize = 10;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listDeletedMovies = services.getDeletedMovieView().OrderBy(x => x.MovieName);
            PagedList<MovieView> lst = new PagedList<MovieView>(listDeletedMovies, pageNumber, pageSize);
            return View(lst);
        }

        public IActionResult RestoreMovie(int movieId)
        {
            SetMenuUser();
            var result = services.restoreMovie(movieId);
            if (result)
            {
                TempData["MessageRestore"] = "Phim này đã được khôi phục";
            }
            return RedirectToAction("DeletedMovies");
        }

        public IActionResult Revenues(int? page)
        {
            SetMenuUser();
            int pageSize = 10;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listBill = services.getAllBill();
            PagedList<BillView> lst = new PagedList<BillView>(listBill, pageNumber, pageSize);
            return View(lst);
        }

        public IActionResult UserManagement(int? page)
        {
            SetMenuUser();
            int pageSize = 10;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listUser = services.getAllUserView();
            PagedList<UserView> lst = new PagedList<UserView>(listUser, pageNumber, pageSize);
            return View(lst);
        }

        [HttpGet]
        public IActionResult CreateUser()
        {
            SetMenuUser();
            return View();
        }

        [HttpPost]
        public IActionResult CreateUser(UserView user)
        {
            SetMenuUser();
            user.IsVerify = true;
            var result = services.createUser(user);
            if (result)
            {
                return RedirectToAction("UserManagement");
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult EditUser(int userId)
        {
            SetMenuUser();
            var user = services.getUserById(userId);
            HttpContext.Session.SetString("Avatar", user.Avatar);
            HttpContext.Session.SetString("Password", user.Password);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserView user, IFormFile file)
        {
            SetMenuUser();
            TempData["MessagUpdate"] = "";
            if (file != null)
            {
                string path = Path.Combine(Environment.CurrentDirectory, "UploadedFile");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                using (var fileStream = new FileStream(Path.Combine(path, file.FileName), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                    fileStream.Dispose();
                    fileStream.Close();
                }
                var pathAfterCombine = Path.Combine(Environment.CurrentDirectory, "UploadedFile", file.FileName);
                var resultUpdate = services.UpdateAvatar(pathAfterCombine);
                user.Avatar = resultUpdate;
            }
            else
            {
                user.Avatar = HttpContext.Session.GetString("Avatar");
                HttpContext.Session.Remove("Avatar");
            }
            if (HttpContext.Session.GetString("Password") != user.Password.Trim())
            {
                var encryptPassword = XString.ToMD5(user.Password.Trim());
                user.Password = encryptPassword;
            }
            var result = services.editUser(user);
            if (result)
            {
                return RedirectToAction("UserManagement");
            }

            return View(user);
        }

        public IActionResult DeleteUser(int userId)
        {
            SetMenuUser();
            TempData["MessageDeleteUser"] = "";
            var result = services.deleteUser(userId);
            if (result)
            {
                TempData["MessageDeleteUser"] = "Người dùng này đã được xóa";
            }
            return RedirectToAction("UserManagement");
        }



        public IActionResult Logout()
        {
            SetMenuUser();
            HttpContext.Session.Clear();
            HttpContext.Session.Remove("Email");
            return RedirectToAction("Login", "Access", new { area = "" });
        }

        public void SetMenuUser()
        {
            int userId = int.Parse(HttpContext.Session.GetString("UserId"));
            var user = services.getUserById(userId);
            ViewBag.Avatar = user.Avatar;
        }

    }
}

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/CreateMovie.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "CreateMovie";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using ModelAccess.ViewModel;
@model MovieView
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Thêm Phim</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="CreateMovie">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>      
                    <div class="form-group">
                        <label asp-for="MovieId" class="control-label"></label>
                        <input asp-for="MovieId" class="form-control" />
                        <span asp-validation-for="MovieId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MovieName" class="control-label"></label>
                        <input asp-for="MovieName" class="form-control" />
                        <span asp-validation-for="MovieName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ReleaseDate" class="control-label"></label>
                        <input asp-for="ReleaseDate" class="form-control" />
                        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PosterPath" class="control-label"></label>
                        <input asp-for="PosterPath" class="form-control" />
                        <span asp-validation-for="PosterPath" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Duration" class="control-label"></label>
                        <input asp-for="Duration" class="form-control" />
                        <span asp-validation-for="Duration" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="OverView" class="control-label"></label>
                        <input asp-for="OverView" class="form-control" />
                        <span asp-validation-for="OverView" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="MovieCatalog">Back to List</a>
        </div>
    </div>
</div>

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/CreateUser.cshtml
@{
    ViewData["Title"] = "CreateUser";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ModelAccess.ViewModel;
@model UserView
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Thêm Người Dùng</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="CreateUser">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserType" class="control-label"></label>
                        <input asp-for="UserType" class="form-control" />
                        <span asp-validation-for="UserType" class="text-danger"></span>
                    </div>         
                    <div class="form-group">
                        <label asp-for="Avatar" class="control-label"></label>
                        <input asp-for="Avatar" class="form-control" />
                        <span asp-validation-for="Avatar" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="UserManagement">Back to List</a>
        </div>

    </div>
</div>

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/DeletedMovies.cshtml
@{
    ViewData["Title"] = "DeletedMovies";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ModelAccess.ViewModel;
@using Newtonsoft.Json;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<MovieView>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Phim Đã Xóa</h3>    
        <p>@TempData["MessageRestore"]</p>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">MovieName</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">ReleaseDate</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">AverageRating</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">ViewCount</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">MovieName</th>
                                    <th rowspan="1" colspan="1">ReleaseDate</th>
                                    <th rowspan="1" colspan="1">AverageRating</th>
                                    <th rowspan="1" colspan="1">ViewCount</th>
                                    <th></th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @if (Model != null)
                                {
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MovieName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ReleaseDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.AverageRating)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ViewCount)
                                            </td>
                                            <td>
                                                <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="RestoreMovie" asp-route-movieId="@item.MovieId">Restore</a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("DeletedMovies", new {page = page}),
                            new X.PagedList.Web.Common.PagedListRenderOptions(){
                            LiElementClasses = new List<String> {"page-item"},
                            PageClasses = new List<String> {"page-link"}
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/DetailMovie.cshtml
@{
    ViewData["Title"] = "DetailMovie";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ModelAccess.ViewModel
@model MovieView

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Chi Tiết Phim</h3>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.MovieName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MovieName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ReleaseDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PosterPath)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PosterPath)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Duration)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Duration)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AverageRating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AverageRating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ViewCount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ViewCount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.OverView)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.OverView)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="EditMovie" asp-route-movieId="@Model.MovieId">Edit</a> |
        <a asp-action="MovieCatalog">Back to List</a>
    </div>
</div>

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/MovieCatalog.cshtml
@{
    ViewData["Title"] = "MovieCatalog";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ModelAccess.ViewModel;
@using Newtonsoft.Json;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<MovieView>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Danh Mục Phim</h3>
        <p><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="CreateMovie">Thêm Phim</a></p>
        <p>@TempData["Message"]</p>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">MovieName</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">ReleaseDate</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">AverageRating</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">ViewCount</th>                                 
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">MovieName</th>
                                    <th rowspan="1" colspan="1">ReleaseDate</th>
                                    <th rowspan="1" colspan="1">AverageRating</th>
                                    <th rowspan="1" colspan="1">ViewCount</th>
                                    <th></th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @if (Model != null)
                                {
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MovieName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ReleaseDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.AverageRating)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ViewCount)
                                            </td>                                  
                                            <td>
                                                <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="EditMovie" asp-route-movieId="@item.MovieId">Edit</a> |
                                                <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="DetailMovie" asp-route-movieId="@item.MovieId">Details</a> |
                                                <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="DeleteMovie" asp-route-movieId="@item.MovieId">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("MovieCatalog", new {page = page}),
                            new X.PagedList.Web.Common.PagedListRenderOptions(){
                                LiElementClasses = new List<String> {"page-item"},
                                PageClasses = new List<String> {"page-link"}
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BTLonWebMovie/Areas/Admin/Views/HomeAdmin/UserManagement.cshtml
@{
    ViewData["Title"] = "UserManagement";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ModelAccess.ViewModel;
@using Newtonsoft.Json;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<UserView>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-primary">Người Dùng</h3>
        <p><a asp-area="Admin" asp-controller="HomeAdmin" asp-action="CreateUser">Thêm Người Dùng</a></p>
        <p>@TempData["MessageDeleteUser"]</p>
        <p>@TempData["MessagUpdate"]</p>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">UserName</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">Email</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">PassWord</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">Avatar</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">UserType</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1">IsVerify</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">UserName</th>
                                    <th rowspan="1" colspan="1">Email</th>
                                    <th rowspan="1" colspan="1">PassWord</th>
                                    <th rowspan="1" colspan="1">Avatar</th>
                                    <th rowspan="1" colspan="1">UserType</th>
                                    <th rowspan="1" colspan="1">IsVerify</th>
                                    <th></th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Password)
                                        </td>
                                        <td>
                                            @{
                                                if (@item.Avatar == "Unknown")
                                                {
                                                    <img src="https://firebasestorage.googleapis.com/v0/b/movieweb-de135.appspot.com/o/AvatarUser%2FAvtDefault.jpg?alt=media&token=6436e579-9b8b-4a5a-8f68-7e08371b2483" width="50" height="50" />
                                                }
                                                else
                                                {
                                                    <img src="@item.Avatar" width="50" height="50" />
                                                }
                                            }
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserType)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IsVerify)
                                        </td>
                                        <td>
                                            <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="EditUser" asp-route-userId="@item.UserId">Edit</a> |
                                            <a asp-area="Admin" asp-controller="HomeAdmin" asp-action="DeleteUser" asp-route-userId="@item.UserId">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="pagination">
                            @Html.PagedListPager(Model, page => Url.Action("UserManagement", new {page = page}),
                            new X.PagedList.Web.Common.PagedListRenderOptions(){
                            LiElementClasses = new List<String> {"page-item"},
                            PageClasses = new List<String> {"page-link"}
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>